### ISSUE TITLE
dumb question: how do i install it with this AUR?

### ISSUE THREAD

**Issue by ojnickel** [mk-fg/archlinux-pkgbuilds#1]
I'm arch linux newie. I use normally gentoo, but that's too much for the rpi3 limited resources

**Comment by mk-fg** [comment]
Basically you'd just run "makepkg" in same dir with PKGBUILD file of the package you want, which will build it, then install with `pacman -U mypkg.pkg.tar.xz`.

There's plenty of docs for that ofc, e.g.:

- https://wiki.archlinux.org/index.php/Arch_User_Repository#Build_and_install_the_package
- https://wiki.archlinux.org/index.php/makepkg#Usage

But gist of the whole process:

- `pacman -Syu` (system update, fetch latest pkg index)
- `pacman -S git base-devel`
- `useradd -m makepkg`

- `su - makepkg`
- `git clone --depth=1 https://github.com/mk-fg/archlinux-pkgbuilds/` (`--depth=1` to not bother fetching history)
- `cd archlinux-pkgbuilds/rtl8812au-5.1.5-rpi-git`
- `makepkg` (should get you `rtl8812au-5.1.5-rpi-git-<something>.pkg.tar.xz`)
- `exit` (back to root)

- `pacman -U ~makepkg/archlinux-pkgbuilds/rtl8812au-5.1.5-rpi-git/*.pkg.tar.xz`

Done!

**Comment by mk-fg** [comment]
Oh, also realized that you might've expected a link to binary repo, but I don't have one for these, I'm afraid.

You can create one easily if you want with `repo-add` (comes with pacman) if you want to distribute binary pkgs to bunch of boards efficiently, but note that "rtl8812au" package in particular is dkms module sources, and will have to be built on each board it's installed-to anyway (for whichever kernel(s) is/are installed there).

**Comment by mk-fg** [comment]
Also, RPi3 is not that bad for compiling stuff, tbh, maybe even on par with old celerons, and I've been using gentoo on these for years ;)
