### ISSUE TITLE
Which hostapd do you use, or need to apply which patches?

### ISSUE THREAD

**Issue by yangxuan8282** [mk-fg/archlinux-pkgbuilds#2]
hi, I'm using a raspberry pi 3 and an asus USB-AC56, after install `rtl8812au-5.1.5-rpi-git` driver on archlinux arm, I can setup an AP with [create_ap](https://github.com/oblique/create_ap)(which is a bash scripts, also use hostapd), the speed is 300 Mb/s, write/read file to raspberry pi speed is about 9MB/s (at first the write speed can reach 15 MB/s, but will slow down later).
But I can't create 11AC access point at right speed, when I enable ieee80211ac and 5G, the AP is only 54 Mb/s.
I'm wondering if this is hostapd related, currently I'm using the one from archlinux arm repo, without any other patches.

**Comment by mk-fg** [comment]
Hey,

> 300 Mb/s ... 54 Mb/s

Note that these can indicate mode of connection and probably top bandwidth for that mode, but not the actual performance, so saying "the speed is 300 Mb/s" is kinda misleading, as that's usually not what you'd get from e.g. iperf3 or during normal use.

> Which hostapd do you use, or need to apply which patches?

On a project where I've used that driver - pretty much same configuration as described here:
http://blog.fraggod.net/2017/04/27/wifi-hostapd-configuration-for-80211ac-networks.html

There are links to patches and snippets of hostapd.conf.

hostapd/regdb can also be patched to remove various restrictions mentioned in that blog post above, though it's probably not required.

Exact PKGBUILDs and stuff around them to get patched stuff:

- hostpad: https://gist.github.com/mk-fg/5345bb4fb5559e9f417b3230fcb1a14c
- crda: https://gist.github.com/4c19ddeafdccc92df4eba696465eadb8
- wireless-regdb: https://gist.github.com/49876b214fdef5af2e84a2b09b4d8692

Though you might want to apply same changes to latest versions of these packages, if any.

Note that even though 802.11ac is capable of pretty high bandwidth, you won't get anything more than ~35 MiB/s from RPi3, as that's about where its USB bus gets saturated, from my testing.
RPi3 has USB-connected 100mbit ethernet chip, so limit is shared with that as well (e.g. if you want to forward traffic between wifi-eth).

Hope that helps!

**Comment by yangxuan8282** [comment]
@mk-fg 
Thanks a lot for share PKGBUILDs, I install those 3 packages, but still failed to create 5G AP:

```
sudo hostapd /home/alarm/.config/hostapd/hostapd.conf 
Configuration file: /home/alarm/.config/hostapd/hostapd.conf
Using interface wlan0 with hwaddr e0:3f:49:8d:4f:07 and ssid "piiiiii"
Failed to set beacon parameters
Interface initialization failed
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: Unable to setup interface.
wlan0: interface state DISABLED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
```

and here is my hostapd config file:

```
cat ~/.config/hostapd/hostapd.conf 
# Basic configuration

interface=wlan0
ssid=piiiiii
channel=5

# WPA and WPA2 configuration

macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=Some_PassWord
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP

# Hardware configuration

driver=nl80211
ieee80211ac=1
hw_mode=g
```

Would you mind share your `hostapd.conf`?

**Comment by mk-fg** [comment]
> and here is my hostapd config file:

"channel=5" doesn't exist in 802.11ac and 5GHz band.
Again, check the blog post I've linked above, tried to describe this stuff there.

**Comment by mk-fg** [comment]
>  still failed to create 5G AP:

Also, when you're figuring stuff out, I'd suggest running hostapd with -d option - shows a ton useful info, e.g. which specific parameters it's trying to apply and when.
Though only if you want to read that of course :)

**Comment by yangxuan8282** [comment]
@mk-fg 
sorry for didn't read the blog carefully, just check your blog post again, and use it as my hostapd config, but not so lucky

here is the output with `-d` options:

```
sudo hostapd -d /home/alarm/.config/hostapd/hostapdac.conf 
random: Trying to read entropy from /dev/random
Configuration file: /home/alarm/.config/hostapd/hostapdac.conf
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Supported vendor command: vendor_id=0x1018 subcmd=1
nl80211: Supported vendor command: vendor_id=0x1a11 subcmd=4106
nl80211: Supported vendor command: vendor_id=0x1a11 subcmd=4107
nl80211: Supported vendor event: vendor_id=0x1018 subcmd=0
nl80211: Supported vendor event: vendor_id=0x1018 subcmd=1
nl80211: interface wlan0 in phy phy2
nl80211: Set mode ifindex 5 iftype 3 (AP)
nl80211: Setup AP(wlan0) - device_ap_sme=1 use_monitor=0
nl80211: Subscribe to mgmt frames with AP handle 0x130fb28 (device SME)
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=04
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=0501
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=0504
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=08
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=09
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=0a
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x130fb28 match=7f
nl80211: Enable Probe Request reporting nl_preq=0x130fb90
nl80211: Register frame type=0x40 (WLAN_FC_STYPE_PROBE_REQ) nl_handle=0x130fb90 match=
rfkill: initial event: idx=2 type=1 op=0 soft=0 hard=0
nl80211: Add own interface ifindex 5 (ifidx_reason -1)
nl80211: if_indices[16]: 5(-1)
phy: phy2
BSS count 1, BSSID mask 00:00:00:00:00:00 (0 bits)
wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Previous country code US, new country code US 
nl80211: Regulatory information - country=US
nl80211: 2402-2472 @ 40 MHz 30 mBm
nl80211: 5170-5250 @ 80 MHz 30 mBm
nl80211: 5250-5330 @ 80 MHz 30 mBm
nl80211: 5490-5730 @ 160 MHz 30 mBm
nl80211: 5735-5835 @ 80 MHz 30 mBm
nl80211: 57240-63720 @ 2160 MHz 40 mBm
nl80211: Added 802.11b mode based on 802.11g information
hw vht capab: 0x3c031a2, conf vht capab: 0x0
Completing interface initialization
Mode: IEEE 802.11a  Channel: 36  Frequency: 5180 MHz
DFS 0 channels required radar detection
Could not set channel for kernel driver
Interface initialization failed
wlan0: interface state COUNTRY_UPDATE->DISABLED
wlan0: AP-DISABLED 
wlan0: Unable to setup interface.
hostapd_interface_deinit_free(0x130e8c0)
hostapd_interface_deinit_free: num_bss=1 conf->num_bss=1
hostapd_interface_deinit(0x130e8c0)
wlan0: interface state DISABLED->DISABLED
hostapd_bss_deinit: deinit bss wlan0
wlan0: Deauthenticate all stations
nl80211: sta_remove -> DEL_STATION wlan0 ff:ff:ff:ff:ff:ff --> -22 (Invalid argument)
wlan0: AP-DISABLED 
hostapd_cleanup(hapd=0x130f4a0 (wlan0))
hostapd_free_hapd_data: Interface wlan0 wasn't started
hostapd_interface_deinit_free: driver=0x5a8684 drv_priv=0x130ffe0 -> hapd_deinit
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211: Disable Probe Request reporting nl_preq=0x89b87319
nl80211: Remove monitor interface: refcount=0
nl80211: Remove beacon (ifindex=5)
netlink: Operstate: ifindex=5 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
nl80211: Unsubscribe mgmt frames handle 0x89b873a1 (deinit)
hostapd_interface_free(0x130e8c0)
hostapd_interface_free: free hapd 0x130f4a0
hostapd_cleanup_iface(0x130e8c0)
hostapd_cleanup_iface_partial(0x130e8c0)
hostapd_cleanup_iface: free iface=0x130e8c0
```

```
cat /home/alarm/.config/hostapd/hostapdac.conf 
# https://w1.fi/cgit/hostap/plain/hostapd/hostapd.conf

ssid=my-test-ap
wpa_passphrase=set-ap-password

country_code=US
# ieee80211d=1
# ieee80211h=1

interface=wlan0
driver=nl80211

wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

logger_syslog=0
logger_syslog_level=4
logger_stdout=-1
logger_stdout_level=0

hw_mode=a
ieee80211n=1
require_ht=1
ieee80211ac=1
require_vht=1

vht_oper_chwidth=1
channel=36
vht_oper_centr_freq_seg0_idx=42
```

**Comment by mk-fg** [comment]
```
Completing interface initialization
Mode: IEEE 802.11a  Channel: 36  Frequency: 5180 MHz
DFS 0 channels required radar detection
Could not set channel for kernel driver
Interface initialization failed
```

I think "Could not set channel for kernel driver" is common catch-all error in this case for unsupported channel-related parameters.

I'd probably look for some debug option in kernel driver, see why it rejects the option, as you won't get anything better from hostapd - driver just returns "operation not supported" for these cases iirc and that's all hostapd sees.

Also, please don't post further questions here, I didn't sign up to debug your setup, kernel and drivers, and have shitton of other stuff I need to look into asap myself.
